exports.PCGame = require('./modules/PCGame.module')
exports.ConsoleGame = require('./modules/ConsoleGame.module')
exports.Songs = require('./modules/Songs.module')
exports.Moives = require('./modules/Movies.module')
exports.Tv = require('./modules/Tv.module')